### ISSUE TITLE
Change disableGracefullyDoneCommand to have 1 to disable 1 to stop

### ISSUE THREAD

**Issue by nyodas** [blablacar/go-nerve#38]
We need to be able to chose beetween 
Disabling the service (Stopping the anonce in zk)

And 
Stopping the services with an exec that will ask the service to stop gracefully once the service has stopped being announced

Example use case:
mysql.
replication is laging -> disable the service in zk 
stopping the service -> disable the service in zk && gracefull quit

**Comment by n0rad** [comment]
done in v14 by adding disableShutdownCommand on service and /disable?shutdown=true
